// Generated by scripts/make_imu_header.py from hardware/imu_map.json.
// Do not edit: re-run the generator after re-calibrating.
//
// Rows are the body axes (+X fore, +Y left, +Z up) written in IMU axes, so
// body = GORON_IMU_TO_BODY * imu. Nearest axis alignment is -z,-x,y,
// tilted 4.64 degrees off it -- a real
// mounting offset, reproduced across calibration runs.
#pragma once

static const float GORON_IMU_TO_BODY[3][3] = {
    { 0.014095f,  0.069840f, -0.997459f},
    {-0.999149f, -0.037691f, -0.016758f},
    {-0.038765f,  0.996846f,  0.069249f}
};
