"""Turn hardware/imu_map.json into a header the firmware can compile in.

    uv run python -m scripts.make_imu_header

The firmware needs the same IMU-to-body rotation that scripts/mirror uses, and
two hand-copied matrices drift apart silently -- the symptom is a policy that
behaves as if the robot were tilted, which looks like a bad policy. Generating
the header keeps one source of truth.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "hardware" / "imu_map.json"
OUT = ROOT / "firmware" / "goron" / "src" / "imu_map.h"


def main() -> None:
    d = json.loads(SRC.read_text())
    m = d["matrix"]
    rows = ",\n".join(
        "    {" + ", ".join(f"{v: .6f}f" for v in row) + "}" for row in m
    )
    OUT.write_text(
        f"""// Generated by scripts/make_imu_header.py from hardware/imu_map.json.
// Do not edit: re-run the generator after re-calibrating.
//
// Rows are the body axes (+X fore, +Y left, +Z up) written in IMU axes, so
// body = GORON_IMU_TO_BODY * imu. Nearest axis alignment is {d['nearest_axis_map']},
// tilted {d.get('tilt_from_axis_aligned_deg', 0):.2f} degrees off it -- a real
// mounting offset, reproduced across calibration runs.
#pragma once

static const float GORON_IMU_TO_BODY[3][3] = {{
{rows}
}};
"""
    )
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
